# Generated by Django 2.1.2 on 2018-10-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='hero_youtube_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hero YouTube code'),
        ),
    ]
