
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-14T16:28:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ce0141a115fdf8de8ac1a19d633fe0dae4cc228",
 "version": "2018.09.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
