# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.2.3'
git_version = '5af210ca8a1c73aa6bae8754c9346ec54d0a756e'
