version: '3.2'

services:

  {{ name }}_app: &app
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: {{ name }}
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
    restart: always
    volumes:
      - .:/app:delegated
    {% if not without_postgres and redis %}
    depends_on:
      - postgres
      - redis
    {% elif not without_postgres %}
    depends_on:
      - postgres
    {% elif redis %}
    depends_on:
      - redis
    {% endif %}
    ports:
      - 8080:8080
      - 8081:8081
    command: adev runserver ./{{ name }}/__main__.py -p 8080
  {% if not without_postgres %}

  postgres:
      image: postgres:10
      container_name: {{ name }}_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432:5432
  {% endif %}
  {% if redis %}

  redis:
    image: redis:4
    ports:
        - 6379:6379
  {% endif %}

  test:
    <<: *app
    container_name: {{ name }}_test
    ports:
      - 8082:8082
    command: make _test
