"""sessionlimit

Revision ID: 0002
Revises: 0001
Create Date: 2016-03-17 16:15:25.035823

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('session_time_limit_min', sa.Float(), nullable=True))

        # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('session_time_limit_min')

        # end Alembic commands ###
