"""filename

Revision ID: 0003
Revises: 0002
Create Date: 2016-03-21 00:08:17.476030

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.Text(), nullable=True))

        # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('filename')

        # end Alembic commands ###
