
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-20T11:28:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e70489eae416fddb0d6538e35914342cfa85f881",
 "version": "v0.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
