###############################################################################
# Role: OpenShiftWorker                                                            #
###############################################################################
- name: OpenShiftWorker
  description: |
    OpenShiftWorker role
  CountDefault: 1
  tags:
    - openshift
  networks:
    - InternalApi
    - Storage
    - StorageMgmt
    - Tenant
  # For systems with both IPv4 and IPv6, you may specify a gateway network for
  # each, such as ['ControlPlane', 'External']
  default_route_networks: ['ControlPlane']
  ServicesDefault:
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::Ntp
    - OS::TripleO::Services::OpenShift::Worker
    - OS::TripleO::Services::OpenShift::GlusterFS
