# Generated by Django 2.1.1 on 2018-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Efemeridea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('moretext', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('eguna', models.IntegerField(db_index=True)),
                ('hila', models.IntegerField(db_index=True)),
                ('urtea', models.IntegerField(db_index=True)),
                ('hamarkada', models.IntegerField(db_index=True)),
                ('is_public', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Efemeridea',
                'verbose_name_plural': 'Efemerideak',
                'ordering': ['-date'],
            },
        ),
    ]
