---

# For use with pre-commit.
# See usage instructions at http://pre-commit.com

-   id: pkgcheck
    name: pkgcheck
    description: This hook runs pkgcheck for linting shell scripts
    entry: pkgcheck
    language: python
    types: [shell]
    verbose: true
