# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2018-08-23 08:54:31 UTC
from __future__ import unicode_literals
import datetime

version = "2.0.7"
githash = "54d4ca984ec81321001f72c888076376381ec0a6"


major = 2
minor = 0
bugfix = 7

release = True
timestamp = datetime.datetime(2018, 8, 23, 8, 54, 31)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
