
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-29T15:36:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7c715a0df25fcfe14a71a206f92fe2c1415e5c8",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
