# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class StubXpathModel(Model):
    """StubXpathModel.

    :param query_string:
    :type query_string: str
    :param namespaces:
    :type namespaces: dict[str, str]
    """

    _attribute_map = {
        'query_string': {'key': 'queryString', 'type': 'str'},
        'namespaces': {'key': 'namespaces', 'type': '{str}'},
    }

    def __init__(self, query_string=None, namespaces=None):
        super(StubXpathModel, self).__init__()
        self.query_string = query_string
        self.namespaces = namespaces
