
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-20T19:01:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "132252664ea7ad0dcf9a16c5ce11106cb3c4c434",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
