[tool.poetry]
name = "imagedb"
version = "0.2"
description = "Store images, especially from Clipboard, in a database, and spin an image server (for usage in Jupyter Notebook)."
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
readme = 'README.md'
repository = 'https://github.com/patarapolw/ImageDB'
homepage = 'https://github.com/patarapolw/ImageDB'

[tool.poetry.dependencies]
python = "*"
pillow = "^5.2"
sqlalchemy = "^1.2"
nonrepeat = "^0.1.1"
flask = "^1.0"
python-slugify = "^1.2"
send2trash = "^1.5"
imagehash = "^4.0"
jupyter = "^1.0"
notebook = "^5.6"

[tool.poetry.dev-dependencies]
tinydb = "^3.11"
