version: 2
jobs:
    build:
     docker:
        - image: circleci/python:2.7
          environment:

     steps:
        - checkout
        - run:
            name: deps
            command: |
                #apt install python-pip
                pip install --user --upgrade -r requirements.txt


        - run:
            name: build
            command: |
              python setup.py install --user

        - run:
            name: dt help
            command: |
               export PATH=/home/circleci/.local/bin:$PATH
               dt help

        - run:
            name: dt version
            command: |
               export PATH=/home/circleci/.local/bin:$PATH
               dt version

        - run:
            name: dt aido token
            command: |
               export PATH=/home/circleci/.local/bin:$PATH
               dt aido18 token dt1-XXzMstGtdJhJeXv-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfQj2vduBXhfPjK6FSSCHQZPr986b8tXASH || true
