# Generated by Django 2.0.3 on 2018-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV')], default='csv', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldatarequest',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV')], default='csv', max_length=25),
        ),
    ]
