# Generated by Django 2.0.3 on 2018-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_export', '0002_auto_20180327_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='exported_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldatarequest',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatarequest',
            name='exported_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
