# Generated by Django 2.0.7 on 2018-07-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_export', '0003_auto_20180330_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataRequest',
        ),
        migrations.RemoveField(
            model_name='historicaldatarequest',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDataRequest',
        ),
    ]
