- block:
  - name: verify that configured SSH private key is a file and has permissions of 0600
    local_action: file path="{{ ansible_ssh_private_key_file }}" state=file mode=0600
    tags:
      - skip_ansible_lint

  - name: construct command line for SSH check
    set_fact:
      check_ssh_cmd: >-
        ansible --ssh-extra-args='-o StrictHostKeyChecking=no'
        -i '{{ inventory_dir }}/{{ (inventory_file | string | default('')) | basename }}'
        {{ host }} -m ping

  - name: check for SSH connectivity and authentication
    local_action: shell {{ check_ssh_cmd }}
    register: result
    changed_when: "result.rc != 0"
    until: result.rc == 0
    retries: "{{ ssh_retries }}"
    delay: "{{ ssh_retry_delay }}"
    tags:
      - skip_ansible_lint
  when: ansible_connection == 'ssh'
