[tool.poetry]
name = "thorod"
description = "A CLI utility for torrent creation and manipulation."
version = "1.0.1"

license = "MIT"

authors = ["thebigmunch <mail@thebigmunch.me>"]

readme = "README.md"

repository = "https://github.com/thebigmunch/thorod"
homepage = "https://github.com/thebigmunch/thorod"

[tool.poetry.dependencies]
python = "^3.6"

appdirs = "^1.4"
click = "^6.0"
click-default-group = "^1.2"
pendulum = "^2.0"
sortedcontainers = "^2.0"
toml = "^0.9.4"
tqdm = "^4.19"

flake8 = { version = "^3.5", optional = true }
flake8-builtins = { version = "^1.0", optional = true }
flake8-import-order = { version = "^0.18", optional = true }
flake8-import-order-tbm = { version = "^1.0.0", optional = true }
poetry = { version = "^0.9", optional = true }
sphinx = { version = "^1.7", optional = true }
sphinx-click = { version = "^1.0", optional = true }

[tool.poetry.extras]
dev = [ "flake8", "flake8-builtins", "flake8-import-order", "flake8-import-order-tbm", "poetry", "sphinx", "sphinx-click" ]
doc = [ "sphinx", "sphinx-click" ]
lint = [ "flake8", "flake8-builtins", "flake8-import-order", "flake8-import-order-tbm" ]

[tool.poetry.scripts]
thorod = "thorod.cli:thorod"
