
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-28T15:58:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "450f54be9cb7efab5a6c58fd04237694bb9429fb",
 "version": "6.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
