
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-27T21:24:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b52d345edc65903749661f1ba48ddaf6466dfe6d",
 "version": "4.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
