
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-19T18:31:30-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fd395cd93b973dbea03bf59ae5e9b397f6a7d49",
 "version": "v0.1.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
