
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-18T16:14:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a890ff6275ef9bfa8051033f055f18f252ffcac9",
 "version": "5.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
