# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgoogleanalytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=32, unique=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgoogleanalytics.CredentialsModel')),
            ],
        ),
    ]
