# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgoogleanalytics', '0002_analyticsprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedpattern',
            name='site',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='site',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='start_date',
        ),
    ]
