# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgoogleanalytics', '0003_auto_20161207_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='photo_src',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
