# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgoogleanalytics', '0005_auto_20161207_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagepath', models.CharField(max_length=255)),
                ('content_type', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('added_at', models.DateField()),
                ('added_day', models.IntegerField(default=0)),
                ('added_week', models.IntegerField(default=0)),
                ('added_month', models.IntegerField(default=0)),
                ('added_year', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField(choices=[(0, b'1d'), (1, b'2d'), (2, b'1w'), (3, b'2w'), (4, b'1m'), (5, b'2m'), (6, b'1y'), (7, b'2y'), (8, b'5y'), (9, b'10y'), (10, b'20y')])),
                ('pageviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgoogleanalytics.Page')),
            ],
        ),
    ]
