# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.BooleanField(default=False)),
                ('end_point', models.URLField()),
                ('token', models.CharField(max_length=50)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
