
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-17T13:02:13+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "371ffbb02f8301046ea1a8dd690e7e092298a320",
 "version": "v0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
