
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-12T12:17:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "af68f5f8546ccb3b000c8e4aa031a9fc29cbdc20",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
