
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0e9f0c2d94cbaa7eb25125b984aca6737157d4bd",
 "version": "0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
