
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-13T16:38:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e9e1599675a1d1bb7b041247dbfe591310757c9",
 "version": "2018.09.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
