
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-17T12:00:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "58b922a71c25cb7e1834859f34fbbb44e5d441c7",
 "version": "6.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
