

TOP_LEFT_CORNER = 'TOP_LEFT_CORNER '
TOP = 'TOP'
TOP_RIGHT_CORNER = 'TOP_LEFT_CORNER'
RIGHT = 'RIGHT'
BOTTOM_RIGHT_CORNER = 'TOP_RIGHT_CORNER'
BOTTOM = 'BOTTOM'
BOTTOM_LEFT_CORNER = 'BOTTOM_RIGHT_CORNER'
LEFT = 'LEFT'


NEIGHBORS = {
    TOP_LEFT_CORNER: (-1, -1),
    TOP: (0, 1),
    TOP_RIGHT_CORNER: (1, 1),
    RIGHT: (1, 0),
    BOTTOM_RIGHT_CORNER: (1, 1),
    BOTTOM: (0, -1),
    BOTTOM_LEFT_CORNER: (-1, -1),
    LEFT: (-1, 0)
}
