
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8bc80bf5cf501f194dbe8dbd911152ccaa59ac4d",
 "version": "0.1.0.b2727"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
