language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
branches:
  only:
    - master
    - 1.1.x
python:
  - 2.7
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - pip install -U setuptools==18.2
  - python bootstrap-buildout.py --setuptools-version=18.2 -c travis.cfg
  - bin/buildout -Nc travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/code-analysis
  - bin/test --all
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls
