[tool.poetry]
name = "adroit"
version = "0.1"
description = "Ansible Docker Role Testing"
authors = ["Andreas Lutro <anlutro@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
ansible = "*"
pytest = "*"

[tool.poetry.scripts]
adroit = 'adroit.cli:main'
