import numpy

DEFAULT_MAX_PVALUE_SE = 0.05
DEFAULT_PARAMETER_SMOOTHING_METHOD = 'savgol'
SAVGOL_DEFAULT_WINDOW_SIZE = 5
MAX_PSCORE = 744.44007192138122
MIN_PVALUE = numpy.exp(-MAX_PSCORE)
DEFAULT_NUM_FIT_POINTS = 20
DEFAULT_PVALUE_CV = 0.1

from . import distributions

DEFAULT_DISTRO_CLASS = distributions.PiecewiseApproxLinear
