#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['BlenderBatchExporter']

package_data = \
{'': ['*']}

setup(name='BlenderBatchExporter',
      version='0.1',
      description='Batch process blend files',
      author='Oliver Dew',
      author_email='olidew@gmail.com',
      url='https://github.com/Utsira/BlenderBatchExporter',
      packages=packages,
      package_data=package_data,
     )
