name: nlpiaenv

channels:
  - conda-forge
  - defaults

dependencies:
  - opencv=3.3.0
  - redis-py>=2.10.6
  - matplotlib=2.2.2
  - pillow=4.3.0
  - plac>=0.9.6,<0.10.0
  - pyqt=5.6.0
  - pandoc=2.1.2
  - plotly>=3.1.1,<3.2.0
  - keras>=2.2.2,<2.3.0
  - keras-preprocessing>=1.0.2,<1.1.0
  - keras-applications>=1.0.4,<1.1.0
  - tensorflow=1.10.0
  - spacy=2.0.12
  - swig=3.0.12
  - nltk=3.2.5
  - gensim=3.4.0
  - python-levenshtein=0.12.0
  - boto3

  - pip:
    - -r ../requirements/requirements-base.txt

