URL = "https://api.verigator.com"

CREATE_SERVICE = "v1/service/service"
GET_SERVICE = "v1/service/service/{}"
DELETE_SERVICE = "v1/service/service/{}"
GET_USERS = "v1/service/service/{}/users"
GET_USER = "v1/service/service/{}/users/{}"
CREATE_USER = "v1/service/service/{}/users"
DELETE_USER = "v1/service/service/{}/users/{}"
AUTH_INITIATE = "v1/service/service/{}/users/{}/auth"
AUTH_VERIFY = "v1/service/service/{}/users/{}/auth"
