# Generated by Django 2.1.1 on 2018-09-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='preview',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
