# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0 - 1.2), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.2
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot2
from purity_fb_1dot2.rest import ApiException
from purity_fb_1dot2.models.array_s3_performance_response import ArrayS3PerformanceResponse


class TestArrayS3PerformanceResponse(unittest.TestCase):
    """ ArrayS3PerformanceResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArrayS3PerformanceResponse(self):
        """
        Test ArrayS3PerformanceResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot2.models.array_s3_performance_response.ArrayS3PerformanceResponse()
        pass


if __name__ == '__main__':
    unittest.main()
