# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.0
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot0
from purity_fb_1dot0.rest import ApiException
from purity_fb_1dot0.apis.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """ AuthenticationApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot0.apis.authentication_api.AuthenticationApi()

    def tearDown(self):
        pass

    def test_login(self):
        """
        Test case for login

        
        """
        pass

    def test_logout(self):
        """
        Test case for logout

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
