# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0 - 1.2), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.2
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot2
from purity_fb_1dot2.rest import ApiException
from purity_fb_1dot2.apis.alert_watchers_api import AlertWatchersApi


class TestAlertWatchersApi(unittest.TestCase):
    """ AlertWatchersApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot2.apis.alert_watchers_api.AlertWatchersApi()

    def tearDown(self):
        pass

    def test_create_alert_watchers(self):
        """
        Test case for create_alert_watchers

        
        """
        pass

    def test_delete_alert_watchers(self):
        """
        Test case for delete_alert_watchers

        
        """
        pass

    def test_list_alert_watchers(self):
        """
        Test case for list_alert_watchers

        
        """
        pass

    def test_test_alert_watchers(self):
        """
        Test case for test_alert_watchers

        
        """
        pass

    def test_update_alert_watchers(self):
        """
        Test case for update_alert_watchers

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
