# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.0
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot0
from purity_fb_1dot0.rest import ApiException
from purity_fb_1dot0.models.pure_object import PureObject


class TestPureObject(unittest.TestCase):
    """ PureObject unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPureObject(self):
        """
        Test PureObject
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot0.models.pure_object.PureObject()
        pass


if __name__ == '__main__':
    unittest.main()
