# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
      python -m pip install --upgrade pip && pip3 install --upgrade setuptools gnureadline
      pip install -e .
  displayName: 'Upgrade pip and setuptools'
  continueOnError: false

- script: pip install tox
  displayName: 'Install tox'

- script: tox
  displayName: 'Test with tox'
