
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-19T19:48:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "57a71377c992753327a16b417daf79df7f506dd1",
 "version": "0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
