#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['BlenderBatchExporter']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['batchExportObj = BlenderBatchExporter:main']}

setup(name='BlenderBatchExporter',
      version='0.2',
      description='Batch process blend files',
      author='Oliver Dew',
      author_email='olidew@gmail.com',
      url='https://github.com/Utsira/BlenderBatchExporter',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
      python_requires='>=3',
     )
