# Generated by Django 2.1 on 2018-10-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0010_auto_20181001_2103'),
        ('ambition_subject', '0020_auto_20180906_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodresult',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalbloodresult',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalsubjectreconsent',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='subjectreconsent',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreconsent',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreconsent',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subjectreconsent',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subjectreconsent',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
    ]
