# Generated by Django 2.1 on 2018-10-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0023_auto_20181001_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodresult',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='bloodresult',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalbloodresult',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalbloodresult',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalsubjectreconsent',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalsubjectreconsent',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='subjectreconsent',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='subjectreconsent',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
    ]
