# Generated by Django 2.1 on 2018-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_subject', '0024_auto_20181002_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbloodresult',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalsubjectreconsent',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='subjectreconsent',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
