# Generated by Django 2.0 on 2018-01-11 06:46

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('task_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_index=True, null=True, size=None)),
            ],
        ),
    ]
