
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-12T17:32:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aaf97b3933859dd6ff5a4230ecfffc4523cb02ce",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
