
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-01T16:38:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "312afb1c242117b71b5fb3b2d7119f7e1e5a5b45",
 "version": "v1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
