language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install codecov
    - pip install pipenv
    - pipenv install --dev
script:
    - pipenv run pytest --verbose --cov atmosphere --cov-report xml --junit-xml pytest.xml
    - pipenv run behave --tags=-@xfail --format=progress3 --junit --junit-directory behave_reports features
after_success:
    - codecov
    - coveralls
notifications:
    webhooks: https://www.travisbuddy.com/
