---
- name: Install packages
  package: name={{ item }} state=present update_cache=yes
  with_items:
    - ca-certificates
    - curl

- include: ubuntu.yml
  when:
    ansible_pkg_mgr == 'apt'

- include: centos.yml
  when:
    ansible_pkg_mgr == 'yum'
