
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-29T15:22:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd5b2766aa47217bf66e4ce54437dbff2687d56c",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
