
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-12T09:49:51+0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cacf38ce99f70dc58e6e4f78297d4fda9aa3d7b",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
