
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d0512644f4c88343400bd424e1b81c75f68e2691",
 "version": "0.6.0-alpha2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
