package:
  name: 'tofu'
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/ToFuProject/tofu.git
  #git_branch: {{ environ['TRAVIS_BRANCH'] }}
  git_rev: {{ environ['REV'] }}

build:
  script_env:
    - REV
    - VERSION
    - TRAVIS_BRANCH
    - CONDA_BLD_PATH
    - PCK

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - cython
    - nose
    - pygments
    - {{ environ['PCK'] }}

  run:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - scipy
    - matplotlib
    - cython
    - nose
    - pygments
    - {{ environ['PCK'] }}

test:
  imports:
    - tofu.geom

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Tomography for Fusion
