# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sceneviewereditorwidget.ui'
#
# Created: Tue Aug 11 15:48:44 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SceneviewerEditorWidget(object):
    def setupUi(self, SceneviewerEditorWidget):
        SceneviewerEditorWidget.setObjectName("SceneviewerEditorWidget")
        SceneviewerEditorWidget.resize(227, 689)
        self.verticalLayout = QtGui.QVBoxLayout(SceneviewerEditorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_all_button = QtGui.QPushButton(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_all_button.sizePolicy().hasHeightForWidth())
        self.view_all_button.setSizePolicy(sizePolicy)
        self.view_all_button.setObjectName("view_all_button")
        self.verticalLayout.addWidget(self.view_all_button)
        self.perspective_checkbox = QtGui.QCheckBox(SceneviewerEditorWidget)
        self.perspective_checkbox.setChecked(True)
        self.perspective_checkbox.setObjectName("perspective_checkbox")
        self.verticalLayout.addWidget(self.perspective_checkbox)
        self.view_angle_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.view_angle_label.setObjectName("view_angle_label")
        self.verticalLayout.addWidget(self.view_angle_label)
        self.view_angle = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_angle.sizePolicy().hasHeightForWidth())
        self.view_angle.setSizePolicy(sizePolicy)
        self.view_angle.setObjectName("view_angle")
        self.verticalLayout.addWidget(self.view_angle)
        self.eye_point_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.eye_point_label.setObjectName("eye_point_label")
        self.verticalLayout.addWidget(self.eye_point_label)
        self.eye_point = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eye_point.sizePolicy().hasHeightForWidth())
        self.eye_point.setSizePolicy(sizePolicy)
        self.eye_point.setObjectName("eye_point")
        self.verticalLayout.addWidget(self.eye_point)
        self.lookat_point_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.lookat_point_label.setObjectName("lookat_point_label")
        self.verticalLayout.addWidget(self.lookat_point_label)
        self.lookat_point = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lookat_point.sizePolicy().hasHeightForWidth())
        self.lookat_point.setSizePolicy(sizePolicy)
        self.lookat_point.setObjectName("lookat_point")
        self.verticalLayout.addWidget(self.lookat_point)
        self.up_vector_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.up_vector_label.setObjectName("up_vector_label")
        self.verticalLayout.addWidget(self.up_vector_label)
        self.up_vector = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_vector.sizePolicy().hasHeightForWidth())
        self.up_vector.setSizePolicy(sizePolicy)
        self.up_vector.setObjectName("up_vector")
        self.verticalLayout.addWidget(self.up_vector)
        self.clipping_planes_groupbox = QtGui.QGroupBox(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clipping_planes_groupbox.sizePolicy().hasHeightForWidth())
        self.clipping_planes_groupbox.setSizePolicy(sizePolicy)
        self.clipping_planes_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.clipping_planes_groupbox.setObjectName("clipping_planes_groupbox")
        self.formLayout = QtGui.QFormLayout(self.clipping_planes_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.near_clipping_label = QtGui.QLabel(self.clipping_planes_groupbox)
        self.near_clipping_label.setObjectName("near_clipping_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.near_clipping_label)
        self.far_clipping_label = QtGui.QLabel(self.clipping_planes_groupbox)
        self.far_clipping_label.setObjectName("far_clipping_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.far_clipping_label)
        self.near_clipping_slider = QtGui.QSlider(self.clipping_planes_groupbox)
        self.near_clipping_slider.setMaximum(10000)
        self.near_clipping_slider.setPageStep(100)
        self.near_clipping_slider.setTracking(True)
        self.near_clipping_slider.setOrientation(QtCore.Qt.Horizontal)
        self.near_clipping_slider.setObjectName("near_clipping_slider")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.near_clipping_slider)
        self.far_clipping_slider = QtGui.QSlider(self.clipping_planes_groupbox)
        self.far_clipping_slider.setMaximum(10000)
        self.far_clipping_slider.setPageStep(100)
        self.far_clipping_slider.setOrientation(QtCore.Qt.Horizontal)
        self.far_clipping_slider.setObjectName("far_clipping_slider")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.far_clipping_slider)
        self.verticalLayout.addWidget(self.clipping_planes_groupbox)
        self.background_colour_label = QtGui.QLabel(SceneviewerEditorWidget)
        self.background_colour_label.setObjectName("background_colour_label")
        self.verticalLayout.addWidget(self.background_colour_label)
        self.background_colour = QtGui.QLineEdit(SceneviewerEditorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_colour.sizePolicy().hasHeightForWidth())
        self.background_colour.setSizePolicy(sizePolicy)
        self.background_colour.setObjectName("background_colour")
        self.verticalLayout.addWidget(self.background_colour)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(SceneviewerEditorWidget)
        QtCore.QObject.connect(self.view_all_button, QtCore.SIGNAL("clicked()"), SceneviewerEditorWidget.viewAll)
        QtCore.QObject.connect(self.perspective_checkbox, QtCore.SIGNAL("clicked(bool)"), SceneviewerEditorWidget.perspectiveStateChanged)
        QtCore.QObject.connect(self.view_angle, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.viewAngleEntered)
        QtCore.QObject.connect(self.eye_point, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.eyePointEntered)
        QtCore.QObject.connect(self.lookat_point, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.lookatPointEntered)
        QtCore.QObject.connect(self.up_vector, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.upVectorEntered)
        QtCore.QObject.connect(self.near_clipping_slider, QtCore.SIGNAL("valueChanged(int)"), SceneviewerEditorWidget.nearClippingChanged)
        QtCore.QObject.connect(self.far_clipping_slider, QtCore.SIGNAL("valueChanged(int)"), SceneviewerEditorWidget.farClippingChanged)
        QtCore.QObject.connect(self.background_colour, QtCore.SIGNAL("editingFinished()"), SceneviewerEditorWidget.backgroundColourEntered)
        QtCore.QMetaObject.connectSlotsByName(SceneviewerEditorWidget)

    def retranslateUi(self, SceneviewerEditorWidget):
        SceneviewerEditorWidget.setWindowTitle(QtGui.QApplication.translate("SceneviewerEditorWidget", "Sceneviewer Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.view_all_button.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.perspective_checkbox.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Perspective projection", None, QtGui.QApplication.UnicodeUTF8))
        self.view_angle_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "View angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.eye_point_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Eye point:", None, QtGui.QApplication.UnicodeUTF8))
        self.lookat_point_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Look at point:", None, QtGui.QApplication.UnicodeUTF8))
        self.up_vector_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Up vector:", None, QtGui.QApplication.UnicodeUTF8))
        self.clipping_planes_groupbox.setTitle(QtGui.QApplication.translate("SceneviewerEditorWidget", "Clipping planes:", None, QtGui.QApplication.UnicodeUTF8))
        self.near_clipping_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Near:", None, QtGui.QApplication.UnicodeUTF8))
        self.far_clipping_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Far:", None, QtGui.QApplication.UnicodeUTF8))
        self.background_colour_label.setText(QtGui.QApplication.translate("SceneviewerEditorWidget", "Background colour R, G, B:", None, QtGui.QApplication.UnicodeUTF8))

