language: python
sudo: required
python:
- '2.7'
- '3.6'
install:
- pip install coveralls
- pip install -r test_requirements.txt
- python setup.py develop
script:
- coverage run -m py.test
after_succes:
- coveralls
deploy:
  provider: pypi
  user: choppsv1
  password:
    secure: EbGOXqI03LC/99SBrTQrOWrXxaeFQl+8eEZboLP6BzUzJ2azIh4JM7VZmlQwSCBb9UrYAciCydKIqWFP5xVLbrbn7AHgayK9lfqLTdwlE1Ph7x9LLCRmVDGJhH5Wiod6VN7FJts2337B6e+BKoMzq4OJqdukNwG/ipHFp42myQ4I8lkjLJ6nzeCpj0x58bmWEcedOjSOEJV8v0WWHMN1We86wd9pYUqFYb4tAjSvMxxbuuxcHiiwISN8E8gFCx89tMCA48FUSMgYQbKB+mmHDWxdO1vd6nH1ddlEmhBd/poV/aryKKQJr+F/8y9Jls3cpAbVtkXgUGolND42L52qokwRrwqzfHtATYJPWSIvvqdOHGsZTfA3anWSCKjXwKgQAUsfJnXSgcaG7H5GoCkz6QbXKmkj1uZAqyNTIHxRs2nboFBsHTJWJh30ouYqIInAZn45eT+iA2SLorLuVR/PUIv+eyGlFh2wbJVROrTV9m2HfEphDWt/0kTYNYfMC4jS7HChWTRO+GYDlpSlXcygEG0WDSmpEKLI/dM4tg6vDzQpFGrnXR9Nh7GYQQjWuV1L/FHUKcPvHfq6VSyZ1Vrq0oTpWbWkQdKwHo53WHOFHUOY53CCLBKqB63RDZ09SsvI0uqAg7L7nWjoR/I0yCMB0rKChTMXX5JeDKwz/7oulTc=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  distributions: sdist bdist_wheel
  edge:
    branch: v1.8.45
env:
  global:
    secure: EbGOXqI03LC/99SBrTQrOWrXxaeFQl+8eEZboLP6BzUzJ2azIh4JM7VZmlQwSCBb9UrYAciCydKIqWFP5xVLbrbn7AHgayK9lfqLTdwlE1Ph7x9LLCRmVDGJhH5Wiod6VN7FJts2337B6e+BKoMzq4OJqdukNwG/ipHFp42myQ4I8lkjLJ6nzeCpj0x58bmWEcedOjSOEJV8v0WWHMN1We86wd9pYUqFYb4tAjSvMxxbuuxcHiiwISN8E8gFCx89tMCA48FUSMgYQbKB+mmHDWxdO1vd6nH1ddlEmhBd/poV/aryKKQJr+F/8y9Jls3cpAbVtkXgUGolND42L52qokwRrwqzfHtATYJPWSIvvqdOHGsZTfA3anWSCKjXwKgQAUsfJnXSgcaG7H5GoCkz6QbXKmkj1uZAqyNTIHxRs2nboFBsHTJWJh30ouYqIInAZn45eT+iA2SLorLuVR/PUIv+eyGlFh2wbJVROrTV9m2HfEphDWt/0kTYNYfMC4jS7HChWTRO+GYDlpSlXcygEG0WDSmpEKLI/dM4tg6vDzQpFGrnXR9Nh7GYQQjWuV1L/FHUKcPvHfq6VSyZ1Vrq0oTpWbWkQdKwHo53WHOFHUOY53CCLBKqB63RDZ09SsvI0uqAg7L7nWjoR/I0yCMB0rKChTMXX5JeDKwz/7oulTc=
