
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-17T09:56:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "57aeb70b96396021b2b996a49e6625e0a547609f",
 "version": "1.23.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
