
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-19T08:21:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cc6034ee07802948f51184979e9707f9628209e",
 "version": "1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
