# Generated by Django 2.0.6 on 2018-08-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('released', 'Released'), ('arcive', 'Arcive')], default='new', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('categorys', models.ManyToManyField(blank=True, related_name='posts', to='data.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PostOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(choices=[('facebook', 'facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poston', to='data.Post')),
            ],
        ),
    ]
