
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-26T20:06:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "871d00daeaf5944a61d9dfc2c0671516e2e971ff",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
