language: python
services:
- rabbitmq
- mysql
env:
- MYSQL_ENV_MYSQL_USER=travis MYSQL_ENV_MYSQL_PASSWORD=
stages:
- lint
- test
- deploy
".before_script": &2
- mysql -e 'CREATE DATABASE pacifica_cart;'
- pushd travis/archive; ArchiveInterface --config config.cfg & popd
- pushd travis/cartd; CartServer & celery -A cart worker -l info -P solo & popd
- sleep 4
- python test_files/archiveinterfacepreload.py
".script": &1
- coverage run --include='pacifica/*' -m pytest -v
- coverage report -m --fail-under 100
- if [[ $CODECLIMATE_REPO_TOKEN ]] ; then codeclimate-test-reporter; fi
jobs:
  include:
  - stage: lint
    python: 3.6
    script: pre-commit run -a
  - python: 2.7
    script: pre-commit run -a
  - stage: test
    script: *1
    before_script: *2
    python: 3.6
  - script: *1
    before_script: *2
    python: 2.7
  - stage: deploy
    services: []
    language: python
    before_install: skip
    script: skip
    python: 3.6
    deploy:
      skip_cleanup: true
      provider: pypi
      user: dmlb2000
      distributions: sdist bdist_wheel
      password:
        secure: Lfg7Bb1DCcBzuKNVT7xeqhlR9kRz33CSon38j0gQ3o1/P4GA8oasUaqRRyyTyflkthDFxaR/d3qIDXRoQ+g0LaVoffOxW0V/f3krxgRPM4IYgcSfVMwhbz2RDC5U/o6a0H/jN9PO+UlY2diWLKFSmpIKe9o0U23IfKue6qPrKcrAJCQsVC4rOckL74rTO3zA6Z2w4x0LkR2T40oDbi/RjcEJBNw/Vm2/t3fym3XnFhVPGqPea3n6eS/4yRBcdNeH41uyLImAbdwIgmFDwItxJnQzmXZJyaRJkj8/XJw4ZknWhaR+IbkqNiF3tt3nq77e38ru1iDjY4IJMPoiplL4w09NxOhzGHKV6/kfq1dUqEtjiYbVsFyJcUP5iB9hy0xEwoJA3Y09LsqGfPC34Kg/Dv0fERk/ch6UvTqpDNixZslokhPX4R9IK2OcP1jdk5DZyT4WK7cEnDYNATN+yP49whbunCWSM0UKNn7eUjEuPGwhrfvXX4A1qTnelPD/IXMcszZ7kF73Fre/lldlqtUJRPInWPW39UrYO+JDL7B1YG0/dDfF6pRihmODkTm5/Tvbq3T1HLVUm0nhn/4jOACIp07uL8hQeKf3G51ZGZNUIRyY8sEqiB6VWWEGQVgSx/zlZ6uwftE0voMX7mHoULuEjBDqlCpAI6GFXOd65YlORlI=
      on:
        tags: true
  - services: []
    language: python
    before_install: skip
    script: skip
    python: 2.7
    deploy:
      skip_cleanup: true
      provider: pypi
      user: dmlb2000
      distributions: bdist_wheel
      password:
        secure: Lfg7Bb1DCcBzuKNVT7xeqhlR9kRz33CSon38j0gQ3o1/P4GA8oasUaqRRyyTyflkthDFxaR/d3qIDXRoQ+g0LaVoffOxW0V/f3krxgRPM4IYgcSfVMwhbz2RDC5U/o6a0H/jN9PO+UlY2diWLKFSmpIKe9o0U23IfKue6qPrKcrAJCQsVC4rOckL74rTO3zA6Z2w4x0LkR2T40oDbi/RjcEJBNw/Vm2/t3fym3XnFhVPGqPea3n6eS/4yRBcdNeH41uyLImAbdwIgmFDwItxJnQzmXZJyaRJkj8/XJw4ZknWhaR+IbkqNiF3tt3nq77e38ru1iDjY4IJMPoiplL4w09NxOhzGHKV6/kfq1dUqEtjiYbVsFyJcUP5iB9hy0xEwoJA3Y09LsqGfPC34Kg/Dv0fERk/ch6UvTqpDNixZslokhPX4R9IK2OcP1jdk5DZyT4WK7cEnDYNATN+yP49whbunCWSM0UKNn7eUjEuPGwhrfvXX4A1qTnelPD/IXMcszZ7kF73Fre/lldlqtUJRPInWPW39UrYO+JDL7B1YG0/dDfF6pRihmODkTm5/Tvbq3T1HLVUm0nhn/4jOACIp07uL8hQeKf3G51ZGZNUIRyY8sEqiB6VWWEGQVgSx/zlZ6uwftE0voMX7mHoULuEjBDqlCpAI6GFXOd65YlORlI=
      on:
        tags: true

install:
- pip install -r requirements-dev.txt
