
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-21T14:28:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a38d4dbed97f1f49ba4e5f37449abcd7a3d00697",
 "version": "v0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
