
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-15T08:56:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cb6a9e9d787a2b9c245b7357fe6d6e0cf3166d0",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
