
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-07T13:48:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d51fee78bcc3d7fadb64bc8c2e1b84e9f3dfa5f9",
 "version": "1.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
