
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-24T13:17:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "01e6aab114b0bcdcce48f17a3ed2c2808245869e",
 "version": "0.0.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
