
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-18T09:46:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "756f8bc4187b8d0d82115d8947efbb606152e8ae",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
