sudo: false
language: python
python:
   - "3.6"
before_install:
   - export root_dir="$(python -c 'import sys;print(sys.prefix)')"
install:
   - pip install -U setuptools
   - pip install -U setuptools-scm
   - pip install -U packaging
   - pip install -r requirements.txt
   - pip install -e .
before_script:
   - coverage run -m aakbar
   - export COVERAGE_PROCESS_START="${PWD}/.coveragerc"
script:
   - aakbar --help
   - aakbar set_simplicity_object letterfreq10
   - aakbar demo_simplicity
after_success:
   - coverage combine
   - cp /tmp/.coverage .
   - bash <(curl -s https://codecov.io/bash) -X gcov
