version: "2017-09-20"
dependencies:
- id: image
  type: docker
  ref: pierone.stups.zalan.do/teapot/training-example
  autostart_on_update: false
pipeline:
- id: deployment
  desc: Deploy to $cluster_id
  type: process
  target: $cluster_id
  process: microservice_standard_deployment
  config:
    apply_permanent_resources:
      env:
        TARGET: $cluster_id
        APPLICATION: example-traffic
        IMAGE: pierone.stups.zalan.do/teapot/training-example
        VERSION: "#{CDP_BUILD_VERSION}"
        REPLICAS: "3"
        # This environment variable is used in the example application for
        # this template. You can remove it when adapting it for your
        # project.
        COLOR: "green"
