language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: Z7bB8/kUsHC29yhWIdeNEOvPmsbkiFCRsMwa684UHFh/fS2JXAPb5du9YasvfDzkRHdT6ydBk0D9CuhsA3M+95bOPb7O6ZQrpJWwJYIkamG2FKGUso7TGV4lHMhgz/s2IOLw7vkSHVCdoIcjz+LErmDkaH4YtV5RE/ofX8q5WVIbL8vfvcRyo0y+OYERIc3kUAnOoeVQselyCyjRMXl4/5CErO+NTdTQ4NYGIxCQLcMcGBoi1s9rcqD+frBdLjC+rqcX8G5g7Ro1RlDaNPJo/FuMboP1/W6Y+pmur5JbUxUNRENWsi3eESkNCVG1eT/RgRpJOCUCn7Nn4SQMOJCQ3nJieb6ffarLvqL4g/t8XyCHQzOMJFo9pq0ynCb5E4stuop7luaEAq5h4P6FnSQSSKQ4COIdWbvp9Iz5AsZfg0zaobInnDDdnt9ujTm1gZfrcRVq4GKm0Tetvi6FUv5QhLPoX7MLezF8WsNOAJjlqW1820vef+p55ikQzU5V1dNJUVGbP4lSmK+BkfKzzz7HFqfLOgCulegdDYyEB47VkjFttNsWG6ktid9I5H/JUhDh6BmcoxJF5eNFt4zeESVX3kriL+GnCahd4wvvo7M0kRpcvOBpv7o9YEvaKqstjkLvhXDfb0+SIRYwKXaEtXLwuMMYxbOm1rLNzFokVwe3VgM=
  - secure: pyTnO2ECdlxVmOGo4jTRPb8KsBcaOcq+qGgIH4EJatBewOfmWPd9Zu6exYhNiS8TYAMAtzHqD7CwIWD3L/8TtCzUOPKYyzQ7eqPSO7zKa8povgmQH8gBkgseNLjxOLHONe24xCtl0IxHtK7koiM9mZ9qcQv0mjNOVtRkaiLqrPsI/+ziX25VAJABCnNIlkEv0q0ncSmTfyzHLDWcMEKKwoRVO75zh7iwnDau7b6R+/PVH+xFQo89CeORUMtzSB1hqsFq6ENiSXJ+vJc1bI2+OX450g6a/EX+IAjd8Gxtyj6gTcPCGnDu6djOc8GCIF0Om50oHnDmE7Wp3aWFXQDygtSJ79ahY6yYuTFG6vAsfpQ2Fl9LQf4YVRoO7+36ez0kY5r0JUKajbyXQnrbZRlkhItS/BYAACu9mHTpBCN1swvsF0LuSD5bKTsIOT3H4MPdOZAO2Rgn2rJhYzcKnrckZUmX2Uooqv+OnnuTNcIzKHg3NWf45Dxqjnjmuyh9EKRctSnMGrIlEKR8jlnIecwWqqZ4376m+7Cp+eIlxCB9M8K8jUBN93MHAcZvjP7Vkaft+vE9Cev0iC1uatPMTSSqb543wVEdyoEwGn1UAEDuv1xLigUsOQlCq9WZS4+eTa9uIHf5WJO0wKlFgd8bmjuy6OntxE1H8KlYgEOt0FW4f2s=
  - secure: Cra/SnmFWW6Rq+6p0vwjH4FGuScAIqemfyN0TvZcepDoRHyrDScBcLGL9XRIWCSX2d+j1rWAkt6FRqhl66rEUG8f8ZXKwEiLXdaRslGbMPFKjE3P0gsrb7PTkpDXhG/POHzKAEGBP6eV2pMV8gxKasMmKDDWzdn5H/TnNuZnJPNs0YYWzG8fwzan6yi3j56Xj7k9xLOSJJc2jruesFE5GhloyIH6ld+bqFA9SGSHv1LvTNaDJfOotC8TehnHJjZyauKo4HsEdW8cylTcmdkv+Xkze1BmdwVmQqqt8Ghy9odIdYHf6Fbq1zFf3dBF6FbmVeNqTN1pTYbqGRKP9gD4HIHFn7Ji8swo58vSenDpyfa3S3PLQ94244C7DYY0XIXCezBuUirtC4MAeZBk98YTAyJkGFwnVtvw+cq6NtoftAmKfEPO+G9lrx6QjvHiYPe61Wh20CtCXkx85Spl+ss+Olg/QrXzvlo7zbMSxEqvnsmcAn7Cperkr+Q5Ljthx92ZhXoa/sosnePfgZ5vXx4HZKrHTxbTb54aobqErl/2V/huJKMzuNu6xHhBhVspLTeqxYIwElUv2vB+EcoIujYwoii9da/snr5DqBbKii6ERVo19v8qOG8sz1PToZbLSiVkAWWrbuRCC/BOP9IrKawYQTpuIaJCxaOXhzQqE+qQWBw=
