
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-26T11:45:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1b13874b75bce40e2c320d68e0292d49a5b4b7f",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
