
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-28T08:27:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4e9a921a07f6532aad58755e67f3c3ccb59e922",
 "version": "2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
