
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-19T18:50:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "32846a5234e7587d17619443ab5e10189e9e8f63",
 "version": "1.12.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
