
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-27T09:00:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d41ea0c27f214cca5550511cfc74793757de1169",
 "version": "4.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
