
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-14T09:16:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2c9176bbc4c73d0bc17b2496eb622a5b14f3055",
 "version": "1.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
