# Generated by Django 2.1 on 2018-10-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_ae', '0011_auto_20181001_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aefollowup',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='aefollowup',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='aeinitial',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='aeinitial',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='aetmg',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='aetmg',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalaefollowup',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalaefollowup',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalaeinitial',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalaeinitial',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalaetmg',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalaetmg',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalrecurrencesymptom',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalrecurrencesymptom',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='recurrencesymptom',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='recurrencesymptom',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
    ]
