
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-04T23:26:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dd942c9e408a0f7c6ff580925b2455904abfc8d",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
