# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .htt_placeholder_api import HttPlaceholderAPI
from .version import VERSION

__all__ = ['HttPlaceholderAPI']

__version__ = VERSION

