
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-29T12:52:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "58232fa3342f3180d030f61d0bab58611e9597c3",
 "version": "2018.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
