
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-04T14:00:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e57e0f8363e5a975d9125823c1d2f385f93fc46",
 "version": "0.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
