# Generated by Django 2.1.2 on 2018-10-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0002_auto_20181005_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='unionid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Union Id'),
        ),
    ]
