---
- include: ubuntu.yml
  when:
    ansible_pkg_mgr == 'apt'

- include: centos.yml
  when:
    ansible_pkg_mgr == 'yum'

- name: Start kubelet
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes

- import_tasks: install_kube_prompt_tasks.yml
