
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bd0997cb201baff6d6e47a99a0b6e12d63dacc0d",
 "version": "1.0.0.post.dev427"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
