
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-14T13:23:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc112f1431f2377fa6eac8d9b48c1c1f9294fcaa",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
