
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-12T13:56:18-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d50688ad686eb5f1a347a21a396a7bc7cf5f68b",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
