
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a293d53bb986bc48f106897641391eba94bae6ac",
 "version": "1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
