
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-05T18:49:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "004ca73a34a9c5e9d9cdc54269863589f6e873a5",
 "version": "2018.10.05.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
