
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-13T11:34:35-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7daebe181a0cbc689267883cb418221bd509e1a",
 "version": "v1.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
