sudo: false
dist: trusty
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - check
    - libssl-dev
    - python3-pip
    - valgrind

env:
  global:
    - PYTHON=python3

cache:
  cargo: true
  apt: true
  directories:
  - $HOME/libsodium

install:
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
  - $PYTHON -m pip install --user pytest ecdsa curve25519-donna pyasn1

script:
  - make
  - make lib
  - ./tests/aestst
  - ./tests/test_check
  - CK_TIMEOUT_MULTIPLIER=20 valgrind -q --error-exitcode=1 ./tests/test_check
  - ./tests/test_openssl 1000
  - ITERS=10 $PYTHON -m pytest tests/

