# Generated by Django 2.1.2 on 2018-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logined_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
