adjectives = [
    'attractive',
    'bald',
    'beautiful',
    'chubby',
    'clean',
    'dazzling',
    'drab',
    'elegant',
    'fancy',
    'fit',
    'flabby',
    'glamorous',
    'gorgeous',
    'handsome',
    'long',
    'magnificent',
    'muscular',
    'plain',
    'plump',
    'quaint',
    'scruffy',
    'shapely',
    'short',
    'skinny',
    'stocky',
    'ashy',
    'black',
    'blue',
    'gray',
    'green',
    'icy',
    'lemon',
    'mango',
    'orange',
    'purple',
    'red',
    'salmon',
    'white',
    'yellow',
    'alive',
    'better',
    'careful',
    'clever',
    'famous',
    'gifted',
    'hallowed',
    'helpful',
    'important',
    'mushy',
    'odd',
    'powerful',
    'rich',
    'shy',
    'vast',
    'aggressive',
    'agreeable',
    'ambitious',
    'brave',
    'calm',
    'delightful',
    'eager',
    'faithful',
    'gentle',
    'happy',
    'jolly',
    'kind',
    'lively',
    'nice',
    'obedient',
    'polite',
    'proud',
    'silly',
    'thankful',
    'victorious',
    'witty',
    'wonderful',
    'zealous',
    'angry',
    'bewildered',
    'clumsy',
    'defeated',
    'embarrassed',
    'fierce',
    'grumpy',
    'mysterious',
    'scary',
    'thoughtless',
    'uptight',
    'broad',
    'crooked',
    'curved',
    'deep',
    'flat',
    'high',
    'low',
    'narrow',
    'refined',
    'round',
    'shallow',
    'skinny',
    'square',
    'steep',
    'straight',
    'wide',
    'big',
    'colossal',
    'fat',
    'gigantic',
    'great',
    'huge',
    'immense',
    'large',
    'little',
    'mammoth',
    'massive',
    'microscopic',
    'miniature',
    'petite',
    'puny',
    'scrawny',
    'short',
    'small',
    'tall',
    'teeny',
    'tiny',
    'crashing',
    'deafening',
    'echoing',
    'faint',
    'harsh',
    'hissing',
    'howling',
    'loud',
    'melodic',
    'noisy',
    'purring',
    'quiet',
    'rapping',
    'raspy',
    'rhythmic',
    'screeching',
    'shrilling',
    'squeaking',
    'thundering',
    'tinkling',
    'wailing',
    'whining',
    'whispering',
    'ancient',
    'brief',
    'early',
    'fast',
    'future',
    'late',
    'long',
    'modern',
    'old',
    'old-fashioned',
    'prehistoric',
    'quick',
    'rapid',
    'short',
    'slow',
    'swift',
    'young',
    'acidic',
    'bitter',
    'cool',
    'creamy',
    'delicious',
    'disgusting',
    'fresh',
    'greasy',
    'juicy',
    'hot',
    'moldy',
    'nutritious',
    'nutty',
    'putrid',
    'rancid',
    'ripe',
    'salty',
    'savory',
    'sour',
    'spicy',
    'spoiled',
    'stale',
    'sweet',
    'tangy',
    'tart',
    'tasty',
    'breezy',
    'bumpy',
    'chilly',
    'cold',
    'cool',
    'cuddly',
    'damp',
    'dry',
    'flaky',
    'fluffy',
    'freezing',
    'greasy',
    'hot',
    'icy',
    'loose',
    'melted',
    'prickly',
    'rough',
    'shaggy',
    'sharp',
    'slimy',
    'sticky',
    'strong',
    'tight',
    'uneven',
    'warm',
    'weak',
    'wet',
    'wooden',
    'abundant',
    'billions',
    'enough',
    'few',
    'full',
    'hundreds',
    'incalculable',
    'limited',
    'many',
    'most',
    'millions',
    'numerous',
    'scarce',
    'some',
    'sparse',
    'substantial',
    'thousands'
]


nouns = [
  'leopard',
  'tiger',
  'lion',
  'jaguar',
  'snow leopard',
  'clouded leopard',
  'marbled cat',
  'bay cat',
  'asian golden cat',
  'caracal',
  'african golden cat',
  'serval',
  'pampas cat',
  'pantanal cat',
  'colocolo',
  'geoffroys cat',
  'kodkod',
  'southern tigrina',
  'andean mountain cat',
  'ocelot',
  'oncilla',
  'margay',
  'canadian lynx',
  'eurasian lynx',
  'siberian lynx',
  'bobcat',
  'cougar',
  'jaguarundi',
  'cheetah',
  'fishing cat',
  'leopard cat',
  'sunda leopard cat',
  'flat-headed cat',
  'rusty-spotted cat',
  'pallass cat',
  'jungle cat',
  'sand cat',
  'black-footed cat',
  'european wildcat',
  'african wildcat',
  'chinese mountain cat',
  'domestic cat',
]
