notifications:
  email: false
language: python
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls dist/
deploy:
  provider: releases
  api_key:
    secure: E13+JaCDtuGOIUu7aEIPssgRM/7BSKjK6ukQVzvxHvVQqttco0X0B6N7dtk9alEr0tb8KzdwurNQEIQlndA+KPEkHYyB63o961sPV+e2SOuu6Ht9Klsc2ZMGEFvO4WISfhxNRrlRN+PAOe08rVhzkAO4e66f1id7iG7iuY6pSiEYynfOSoyQYArknL2L4QqxoJ8qTxFGuhjceSxJUCQwaXD7mwz9YSbe0tnJ5ur+WKJKdpvnDmGd7NtQ0risyY3AW0+E9QIewo8+SwhTrC4aDFkFb91sp/626dqs7LEsbw72ppAGUH7CguK6GFwo6NGifXYwzZGX4SKyji2GZlS+DFITM72PYxVR7ZE3E6AW8+XAP8hQCzNRp2Q1KM7WCQl3urxe9GOXGkrp7Smg7QulPCy+OEZuR/2nOamlzBGXKOL8HRtg7qW6nKGgGa8JyrWS9bRsG9IzqNVYllmwbDghhnN+WkNVgBB/C1kVMHDpGqPdtKWJvJx5UL5/RrN0eBeOjUkVD59Sw+tWv+d5pNy+HO91Z3TxFCYQ7Yr0cDVtRFQRYtWtNP4C6x1srVR+Ea/Z0SAVs8SxPEtc8bnsOwTGMKJVs2ZWxrrcT4GPURTvAiy1ow8h/QBieAJ4rcq2Kucbi1XOyiwhXrgyLw7rPzDMm+J40P1IGisQ+gZrA0nz4DI=
  file_glob: true
  file: dist/mapbox_earcut*
  skip_cleanup: true
  on:
    tags: true
    repo: skogler/mapbox_earcut_python
