
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "14db5c8d2e21253f7f9a3f0a265d93108698eca4",
 "version": "0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
