
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1bce581b8d965717fbc9ffd3f96d14210d07bb1e",
 "version": "2006"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
