services:
- postgresql
- mysql
- elasticsearch
- rabbitmq
addons:
  apt:
    sources:
    - elasticsearch-5.x
    packages:
    - elasticsearch
    - oracle-java8-set-default
stages:
- lint
- test
- deploy
env:
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD:
cache: pip
before_install:
- pip install --upgrade pip setuptools wheel
- bash -xe travis/before-install.sh
install:
- pip install -r requirements-dev.txt
".test_job":
  language: python
  stage: test
  script: &2
  - coverage run --include='pacifica/*' -m pytest -v
  - coverage report --show-missing --fail-under 100
  - if [[ $CODECLIMATE_REPO_TOKEN ]] ; then codeclimate-test-reporter ; fi
  - pip install .
  - python setup.py bdist_wheel
  - python setup.py sdist
".lint_job":
  language: python
  stage: lint
  script: &1
  - pre-commit run -a
  - radon cc pacifica
jobs:
  include:
  - language: python
    stage: lint
    script: *1
    python: 3.6
  - language: python
    stage: lint
    script: *1
    python: 2.7
  - language: python
    stage: test
    script: *2
    python: 3.6
  - language: python
    stage: test
    script: *2
    python: 2.7
  - stage: deploy
    services: []
    language: python
    before_install: skip
    script: skip
    python: 3.6
    deploy:
      skip_cleanup: true
      provider: pypi
      user: dmlb2000
      distributions: sdist bdist_wheel
      password:
        secure: ih2ArW9JXkMHeyWydRU12Fw1YYJGt5axgrlgne5C0QX3/qPu46Mr8X7VVOMt6j6O+EHVP+Ph4PUV2qh3juNidxcIyOr+kSVXDWw0MNRQbyenjO02B7SpisdyfmtuRG/PZWhUWQII1ULYPihsDvxc6JOVqzTAYlj2r4Ley9ZTj929lC/JA4dNq4pVhUEXCrtWx/TuX+FWmMwfUqaF6zw3O3/jGrE3Ml0jtR3Jmb/V9t0zAjLD0fGksaaw75qjyNjTLID7EKCLSfAEX+NHwNjypuxpb6shOl+w005MaZzIfk7Wcw35mgU96SON8bKFts648nwyYeZByUkQ76dqkDB6KjTuTNaeHFsuq93oXGmZCcM0QVJVJSz97SgOCJiI3nD1ushQ9TuhU3tdQW1ty5HO7l1lrzfdPQEiVu3PjTURY5ptNOtuemtfrHQiv64Be5iBDnv/BduUpSrWL84MGhygWLyau052wt4ke54gKwH6xbVYcKx15REXJmdYmKQe4cSfxhrHK2/rgw0zTyGf8qrieg3oL2sgb/NpQQIfDUtLvW0n73qiCF/QZ+d5bn7fpB7MY58CGgfTnL33qnfaJnf6nbkg6cc96hGF6qc96ww+F5WqEOrKTfykuiO7N3fYyzmL0zrBzWifUIXDOwzamW6NXLie5WPag+aUdqVlsTsEk88=
      on:
        tags: true
  - stage: deploy
    services: []
    language: python
    before_install: skip
    script: skip
    python: 2.7
    deploy:
      skip_cleanup: true
      provider: pypi
      user: dmlb2000
      distributions: bdist_wheel
      password:
        secure: ih2ArW9JXkMHeyWydRU12Fw1YYJGt5axgrlgne5C0QX3/qPu46Mr8X7VVOMt6j6O+EHVP+Ph4PUV2qh3juNidxcIyOr+kSVXDWw0MNRQbyenjO02B7SpisdyfmtuRG/PZWhUWQII1ULYPihsDvxc6JOVqzTAYlj2r4Ley9ZTj929lC/JA4dNq4pVhUEXCrtWx/TuX+FWmMwfUqaF6zw3O3/jGrE3Ml0jtR3Jmb/V9t0zAjLD0fGksaaw75qjyNjTLID7EKCLSfAEX+NHwNjypuxpb6shOl+w005MaZzIfk7Wcw35mgU96SON8bKFts648nwyYeZByUkQ76dqkDB6KjTuTNaeHFsuq93oXGmZCcM0QVJVJSz97SgOCJiI3nD1ushQ9TuhU3tdQW1ty5HO7l1lrzfdPQEiVu3PjTURY5ptNOtuemtfrHQiv64Be5iBDnv/BduUpSrWL84MGhygWLyau052wt4ke54gKwH6xbVYcKx15REXJmdYmKQe4cSfxhrHK2/rgw0zTyGf8qrieg3oL2sgb/NpQQIfDUtLvW0n73qiCF/QZ+d5bn7fpB7MY58CGgfTnL33qnfaJnf6nbkg6cc96hGF6qc96ww+F5WqEOrKTfykuiO7N3fYyzmL0zrBzWifUIXDOwzamW6NXLie5WPag+aUdqVlsTsEk88=
      on:
        tags: true
