# Generated by Django 2.1 on 2018-10-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0010_auto_20181001_2103'),
        ('ambition_ae', '0010_auto_20180906_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='aefollowup',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='aeinitial',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='aetmg',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalaefollowup',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalaeinitial',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalaetmg',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalrecurrencesymptom',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='recurrencesymptom',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aefollowup',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aeinitial',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aetmg',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaefollowup',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaeinitial',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaetmg',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecurrencesymptom',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecurrencesymptom',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recurrencesymptom',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recurrencesymptom',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
    ]
