
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-10T17:10:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "87ae8a05bb3eeed48dbd1704c4281731069939f0",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
