language: python
python:
  - 3.5

install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
  - "mkdir test_root"
  - "pip install coveralls"
  - "pip install ."

script: make coverage

after_success:
  coveralls

