#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['midgard',
 'midgard.collections',
 'midgard.collections.dataset',
 'midgard.config',
 'midgard.coords',
 'midgard.dev',
 'midgard.files',
 'midgard.math',
 'midgard.parsers']

package_data = \
{'': ['*']}

install_requires = \
['numpy', 'pandas', 'scipy']

entry_points = \
{'console_scripts': ['midgard_release = midgard_release:main']}

setup(name='midgard',
      version='0.1.7',
      description='Midgard, the Python Geodesy library',
      author='Norwegian Mapping Authority',
      author_email='geir.arne.hjelle@kartverket.no',
      url='https://github.com/kartverket/midgard',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
