
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-03T10:42:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "85d88126df4162b4f99cbef1683236c84135f643",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
