# Generated by Django 2.0.6 on 2018-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLxService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.SlugField(verbose_name='organisation')),
                ('service', models.SlugField(verbose_name='service')),
                ('address', models.URLField(help_text='Network-address where this service is provided. Must be the canonical URL.', max_length=255, unique=True, verbose_name='address')),
            ],
            options={
                'verbose_name': 'NLx service',
                'verbose_name_plural': 'NLx services',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nlxservice',
            unique_together={('organisation', 'service')},
        ),
    ]
