# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WidgetEnergystarPlaceDTO(Model):
    """WidgetEnergystarPlaceDTO.

    :param place: Place
    :type place: ~energycap.sdk.models.PlacePlaceChildDTO
    :param address: Address
    :type address: ~energycap.sdk.models.AccountsAddressChildDTO
    :param energystar: Energystar rating
    :type energystar: ~energycap.sdk.models.PlaceEnergyStarRatingChildDTO
    :param is_energystar_turned_on: Boolean for wether or not building is
     submitting to energystar
    :type is_energystar_turned_on: bool
    :param current_area:
    :type current_area: int
    :param current_area_unit:
    :type current_area_unit: str
    """

    _attribute_map = {
        'place': {'key': 'place', 'type': 'PlacePlaceChildDTO'},
        'address': {'key': 'address', 'type': 'AccountsAddressChildDTO'},
        'energystar': {'key': 'energystar', 'type': 'PlaceEnergyStarRatingChildDTO'},
        'is_energystar_turned_on': {'key': 'isEnergystarTurnedOn', 'type': 'bool'},
        'current_area': {'key': 'currentArea', 'type': 'int'},
        'current_area_unit': {'key': 'currentAreaUnit', 'type': 'str'},
    }

    def __init__(self, place=None, address=None, energystar=None, is_energystar_turned_on=None, current_area=None, current_area_unit=None):
        super(WidgetEnergystarPlaceDTO, self).__init__()
        self.place = place
        self.address = address
        self.energystar = energystar
        self.is_energystar_turned_on = is_energystar_turned_on
        self.current_area = current_area
        self.current_area_unit = current_area_unit
