
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d77a71b0ef386a831e5570c5486f919778fa091c",
 "version": "0.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
