
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-20T13:10:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a007239afcfcf81cb4f59569dfab1d8cd917b83e",
 "version": "0.0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
