
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-26T17:39:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "28f1b0f151c338a49282a630f67c27d6fcfbefa5",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
