
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f3c320b5ad99fb24b56188efaf5263e0702f639c",
 "version": "0.1.0.b2696.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
