
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-14T13:47:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1069db81c4e72e9b40704687a3b4e78284bdf4e1",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
