# Generated by Django 2.0.5 on 2018-10-08 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBtcLocalbitcoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_btc_usd_avg_1h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_usd_avg_6h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_usd_avg_12h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_usd_avg_24h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_bs_avg_1h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_bs_avg_6h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_bs_avg_12h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc_bs_avg_24h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'onx_price_btc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceOnix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_onx_buy', models.DecimalField(decimal_places=8, max_digits=20)),
                ('onx_bs_buy', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_onx_buy', models.DecimalField(decimal_places=8, max_digits=20)),
                ('btc_onx_sell', models.DecimalField(decimal_places=8, max_digits=20)),
                ('onx_bs_sell', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_onx_sell', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'onx_historico_price',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Yobit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_onx_sell', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_btc_sell', models.DecimalField(decimal_places=8, max_digits=20)),
                ('btc_onx_buy', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_btc_buy', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'yobit_onix',
                'ordering': ['-created_at'],
            },
        ),
    ]
