# Generated by Django 2.0.5 on 2018-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_onixcoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code_country', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=60, verbose_name='Páis')),
                ('code_currency', models.CharField(max_length=3, verbose_name='Simbolo de moneda')),
            ],
            options={
                'db_table': 'onx_price_country',
            },
        ),
    ]
