# Generated by Django 2.0.5 on 2018-10-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_onixcoin', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebtclocalbitcoin',
            name='country',
            field=models.ForeignKey(default='VEN', on_delete=django.db.models.deletion.PROTECT, to='price_onixcoin.Country'),
        ),
    ]
