# Generated by Django 2.0.5 on 2018-10-08 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_onixcoin', '0003_pricebtclocalbitcoin_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='pricebtclocalbitcoin',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Precios bitcoins'},
        ),
        migrations.AlterModelOptions(
            name='priceonix',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Precios del onix'},
        ),
        migrations.AddField(
            model_name='priceonix',
            name='country',
            field=models.ForeignKey(default='VEN', on_delete=django.db.models.deletion.PROTECT, to='price_onixcoin.Country'),
        ),
        migrations.AlterField(
            model_name='pricebtclocalbitcoin',
            name='price_btc_bs_avg_12h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='BTC EN MONEDA LOCAL AVG 12H'),
        ),
        migrations.AlterField(
            model_name='pricebtclocalbitcoin',
            name='price_btc_bs_avg_1h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='BTC EN MONEDA LOCAL AVG 1H'),
        ),
        migrations.AlterField(
            model_name='pricebtclocalbitcoin',
            name='price_btc_bs_avg_24h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='BTC EN MONEDA LOCAL AVG 24H'),
        ),
        migrations.AlterField(
            model_name='pricebtclocalbitcoin',
            name='price_btc_bs_avg_6h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='BTC EN MONEDA LOCAL AVG 6H'),
        ),
        migrations.AlterField(
            model_name='priceonix',
            name='onx_bs_buy',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='ONX EN MONEDA LOCAL PARA LA COMPRA'),
        ),
        migrations.AlterField(
            model_name='priceonix',
            name='onx_bs_sell',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='ONX EN MONEDA LOCAL PARA LA VENTA'),
        ),
    ]
