# coding: utf-8

# flake8: noqa
"""
    Text Analytics API (v2.0)

    The Text Analytics API is a suite of text analytics web services built with best-in-class Microsoft machine learning algorithms.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/overview  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.batch_input_v2 import BatchInputV2
from swagger_client.models.detected_language_v2 import DetectedLanguageV2
from swagger_client.models.entities_batch_result_item_v2 import EntitiesBatchResultItemV2
from swagger_client.models.entities_batch_result_v2 import EntitiesBatchResultV2
from swagger_client.models.entity_record_v2 import EntityRecordV2
from swagger_client.models.error_record_v2 import ErrorRecordV2
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.input_v2 import InputV2
from swagger_client.models.internal_error import InternalError
from swagger_client.models.key_phrase_batch_result_item_v2 import KeyPhraseBatchResultItemV2
from swagger_client.models.key_phrase_batch_result_v2 import KeyPhraseBatchResultV2
from swagger_client.models.language_batch_result_item_v2 import LanguageBatchResultItemV2
from swagger_client.models.language_batch_result_v2 import LanguageBatchResultV2
from swagger_client.models.match_record_v2 import MatchRecordV2
from swagger_client.models.multi_language_batch_input_v2 import MultiLanguageBatchInputV2
from swagger_client.models.multi_language_input_v2 import MultiLanguageInputV2
from swagger_client.models.object import Object
from swagger_client.models.sentiment_batch_result_item_v2 import SentimentBatchResultItemV2
from swagger_client.models.sentiment_batch_result_v2 import SentimentBatchResultV2
