apiVersion: v1
kind: Service
metadata:
  labels:
    application: "{{{APPLICATION}}}"
  name: "{{{APPLICATION}}}-{{{VERSION}}}"
spec:
  selector:
    application: "{{{APPLICATION}}}"
    version: "{{{VERSION}}}"
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      # this needs to match your container port
      targetPort: 8080
