
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-13T10:32:17-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d90c61032bd24b9a49c71402cb9ccb0e95c7012d",
 "version": "v1.0.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
