
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-05T01:07:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f960ed9d3a8afcc4bdbed1554d7b2fcc929f5b9",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
