
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-17T19:16:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec0ea123bb30a171a13b0cef67769b917e1ba80c",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
