[tool.poetry]
name = "option"
version = "0.1.1"
description = "Rust like Option type in Python"
authors = ["Peijun Ma <peijun.ma@protonmail.com>"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
