
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-05T21:35:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e6fb98a623e7aaf2ceaace387f43c4906905a1d",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
