
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-01T20:02:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9bf55b0f8ec42e959b92ebb06c3329b28dec0f2",
 "version": "2018.10.01.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
