
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-22T21:35:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ae7b993bea5e1128d1f210fb5b17b5658a3fd7f",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
