
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ec27ef20c77562a7e7d43b2edcf02c252116d930",
 "version": "0.1.0.b2696.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
