
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-04T12:25:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f653984e92c0b6a036a1d6181a3a0af9aa7ffa91",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
