
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-06T15:00:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "87d58b2f0ac80516d5fbb6be0cdb854cdc115585",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
