# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created: Sun Sep 23 19:06:41 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 767)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stepSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.stepSpinBox.setObjectName("stepSpinBox")
        self.gridLayout_5.addWidget(self.stepSpinBox, 0, 3, 1, 1)
        self.backwardtimeButton = QtGui.QPushButton(self.layoutWidget)
        self.backwardtimeButton.setObjectName("backwardtimeButton")
        self.gridLayout_5.addWidget(self.backwardtimeButton, 0, 0, 1, 1)
        self.forwardtimeButton = QtGui.QPushButton(self.layoutWidget)
        self.forwardtimeButton.setObjectName("forwardtimeButton")
        self.gridLayout_5.addWidget(self.forwardtimeButton, 0, 1, 1, 1)
        self.tstepLabel = QtGui.QLabel(self.layoutWidget)
        self.tstepLabel.setText("")
        self.tstepLabel.setObjectName("tstepLabel")
        self.gridLayout_5.addWidget(self.tstepLabel, 0, 2, 1, 1)
        self.timeLabel = QtGui.QLabel(self.layoutWidget)
        self.timeLabel.setText("")
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout_5.addWidget(self.timeLabel, 1, 3, 1, 1)
        self.timeSlider = QtGui.QSlider(self.layoutWidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.gridLayout_5.addWidget(self.timeSlider, 1, 0, 1, 3)
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(7, 684, 224, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tiniSpinBox = QtGui.QSpinBox(self.layoutWidget_3)
        self.tiniSpinBox.setObjectName("tiniSpinBox")
        self.horizontalLayout_3.addWidget(self.tiniSpinBox)
        self.tmaxSpinBox = QtGui.QSpinBox(self.layoutWidget_3)
        self.tmaxSpinBox.setObjectName("tmaxSpinBox")
        self.horizontalLayout_3.addWidget(self.tmaxSpinBox)
        self.animationButton = QtGui.QPushButton(self.layoutWidget_3)
        self.animationButton.setObjectName("animationButton")
        self.horizontalLayout_3.addWidget(self.animationButton)
        self.plotButton = QtGui.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(300, 60, 81, 51))
        self.plotButton.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"Helvetica\";\n"
"")
        self.plotButton.setObjectName("plotButton")
        self.phaseComboBox = QtGui.QComboBox(self.centralwidget)
        self.phaseComboBox.setGeometry(QtCore.QRect(245, 264, 131, 26))
        self.phaseComboBox.setObjectName("phaseComboBox")
        self.speciesComboBox = QtGui.QComboBox(self.centralwidget)
        self.speciesComboBox.setGeometry(QtCore.QRect(245, 241, 131, 26))
        self.speciesComboBox.setObjectName("speciesComboBox")
        self.rectangleCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.rectangleCheckBox.setGeometry(QtCore.QRect(320, 358, 51, 20))
        self.rectangleCheckBox.setObjectName("rectangleCheckBox")
        self.coordLabel = QtGui.QLabel(self.centralwidget)
        self.coordLabel.setGeometry(QtCore.QRect(10, 644, 211, 31))
        self.coordLabel.setText("")
        self.coordLabel.setObjectName("coordLabel")
        self.lineCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.lineCheckBox.setGeometry(QtCore.QRect(270, 358, 51, 20))
        self.lineCheckBox.setObjectName("lineCheckBox")
        self.aspectCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.aspectCheckBox.setGeometry(QtCore.QRect(244, 294, 111, 18))
        self.aspectCheckBox.setObjectName("aspectCheckBox")
        self.x1minSlider = QtGui.QSlider(self.centralwidget)
        self.x1minSlider.setGeometry(QtCore.QRect(16, 119, 141, 22))
        self.x1minSlider.setOrientation(QtCore.Qt.Horizontal)
        self.x1minSlider.setObjectName("x1minSlider")
        self.x2minSlider = QtGui.QSlider(self.centralwidget)
        self.x2minSlider.setGeometry(QtCore.QRect(15, 162, 141, 22))
        self.x2minSlider.setOrientation(QtCore.Qt.Horizontal)
        self.x2minSlider.setObjectName("x2minSlider")
        self.x1maxSlider = QtGui.QSlider(self.centralwidget)
        self.x1maxSlider.setGeometry(QtCore.QRect(180, 119, 141, 22))
        self.x1maxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.x1maxSlider.setObjectName("x1maxSlider")
        self.x2maxSlider = QtGui.QSlider(self.centralwidget)
        self.x2maxSlider.setGeometry(QtCore.QRect(179, 161, 141, 22))
        self.x2maxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.x2maxSlider.setObjectName("x2maxSlider")
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 133, 91, 20))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fieldsComboBox = QtGui.QComboBox(self.centralwidget)
        self.fieldsComboBox.setGeometry(QtCore.QRect(245, 220, 131, 26))
        self.fieldsComboBox.setObjectName("fieldsComboBox")
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(225, 224, 20, 35))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fieldButton = QtGui.QRadioButton(self.layoutWidget2)
        self.fieldButton.setText("")
        self.fieldButton.setObjectName("fieldButton")
        self.verticalLayout.addWidget(self.fieldButton)
        self.particleButton = QtGui.QRadioButton(self.layoutWidget2)
        self.particleButton.setText("")
        self.particleButton.setObjectName("particleButton")
        self.verticalLayout.addWidget(self.particleButton)
        self.x1min = QtGui.QLabel(self.centralwidget)
        self.x1min.setGeometry(QtCore.QRect(71, 105, 40, 20))
        self.x1min.setText("")
        self.x1min.setObjectName("x1min")
        self.x2min = QtGui.QLabel(self.centralwidget)
        self.x2min.setGeometry(QtCore.QRect(70, 154, 41, 14))
        self.x2min.setText("")
        self.x2min.setObjectName("x2min")
        self.x2max = QtGui.QLabel(self.centralwidget)
        self.x2max.setGeometry(QtCore.QRect(234, 152, 41, 14))
        self.x2max.setText("")
        self.x2max.setObjectName("x2max")
        self.x1max = QtGui.QLabel(self.centralwidget)
        self.x1max.setGeometry(QtCore.QRect(234, 108, 41, 20))
        self.x1max.setText("")
        self.x1max.setObjectName("x1max")
        self.x1maxLabel = QtGui.QLabel(self.centralwidget)
        self.x1maxLabel.setGeometry(QtCore.QRect(201, 137, 89, 18))
        self.x1maxLabel.setText("")
        self.x1maxLabel.setObjectName("x1maxLabel")
        self.contrastLabel = QtGui.QLabel(self.centralwidget)
        self.contrastLabel.setGeometry(QtCore.QRect(172, 344, 41, 20))
        self.contrastLabel.setText("")
        self.contrastLabel.setObjectName("contrastLabel")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 196, 81, 20))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(223, 202, 101, 20))
        self.label_9.setObjectName("label_9")
        self.xmax_3 = QtGui.QLabel(self.centralwidget)
        self.xmax_3.setGeometry(QtCore.QRect(17, 374, 91, 16))
        self.xmax_3.setObjectName("xmax_3")
        self.slicevalueSlider = QtGui.QSlider(self.centralwidget)
        self.slicevalueSlider.setGeometry(QtCore.QRect(11, 440, 101, 22))
        self.slicevalueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.slicevalueSlider.setObjectName("slicevalueSlider")
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(240, 675, 69, 51))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pngCheckBox = QtGui.QCheckBox(self.layoutWidget3)
        self.pngCheckBox.setObjectName("pngCheckBox")
        self.verticalLayout_5.addWidget(self.pngCheckBox)
        self.movieCheckBox = QtGui.QCheckBox(self.layoutWidget3)
        self.movieCheckBox.setIconSize(QtCore.QSize(25, 16))
        self.movieCheckBox.setObjectName("movieCheckBox")
        self.verticalLayout_5.addWidget(self.movieCheckBox)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(21, 410, 78, 20))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xyButton = QtGui.QRadioButton(self.layoutWidget4)
        self.xyButton.setText("")
        self.xyButton.setObjectName("xyButton")
        self.horizontalLayout.addWidget(self.xyButton)
        self.xzButton = QtGui.QRadioButton(self.layoutWidget4)
        self.xzButton.setText("")
        self.xzButton.setObjectName("xzButton")
        self.horizontalLayout.addWidget(self.xzButton)
        self.yzButton = QtGui.QRadioButton(self.layoutWidget4)
        self.yzButton.setText("")
        self.yzButton.setObjectName("yzButton")
        self.horizontalLayout.addWidget(self.yzButton)
        self.slicevalueLabel = QtGui.QLabel(self.centralwidget)
        self.slicevalueLabel.setGeometry(QtCore.QRect(25, 462, 81, 21))
        self.slicevalueLabel.setText("")
        self.slicevalueLabel.setObjectName("slicevalueLabel")
        self.contrastSlider = QtGui.QSlider(self.centralwidget)
        self.contrastSlider.setGeometry(QtCore.QRect(184, 325, 22, 61))
        self.contrastSlider.setOrientation(QtCore.Qt.Vertical)
        self.contrastSlider.setObjectName("contrastSlider")
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(16, 310, 111, 42))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.simuLabel = QtGui.QLabel(self.layoutWidget5)
        self.simuLabel.setStyleSheet("color: rgb(0,0,255)")
        self.simuLabel.setText("")
        self.simuLabel.setObjectName("simuLabel")
        self.verticalLayout_6.addWidget(self.simuLabel)
        self.coordinateLabel = QtGui.QLabel(self.layoutWidget5)
        self.coordinateLabel.setStyleSheet("color: rgb(0,0,255)")
        self.coordinateLabel.setText("")
        self.coordinateLabel.setObjectName("coordinateLabel")
        self.verticalLayout_6.addWidget(self.coordinateLabel)
        self.amrSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.amrSpinBox.setGeometry(QtCore.QRect(148, 216, 56, 24))
        self.amrSpinBox.setObjectName("amrSpinBox")
        self.yt3DPushButton = QtGui.QPushButton(self.centralwidget)
        self.yt3DPushButton.setGeometry(QtCore.QRect(245, 431, 71, 31))
        self.yt3DPushButton.setObjectName("yt3DPushButton")
        self.visitPushButton = QtGui.QPushButton(self.centralwidget)
        self.visitPushButton.setGeometry(QtCore.QRect(245, 454, 71, 31))
        self.visitPushButton.setObjectName("visitPushButton")
        self.rowpanelSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.rowpanelSpinBox.setGeometry(QtCore.QRect(248, 520, 56, 24))
        self.rowpanelSpinBox.setObjectName("rowpanelSpinBox")
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(308, 521, 71, 21))
        self.label_16.setObjectName("label_16")
        self.columnpanelSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.columnpanelSpinBox.setGeometry(QtCore.QRect(248, 547, 56, 24))
        self.columnpanelSpinBox.setObjectName("columnpanelSpinBox")
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(308, 549, 81, 21))
        self.label_18.setObjectName("label_18")
        self.synctimeBox = QtGui.QCheckBox(self.centralwidget)
        self.synctimeBox.setGeometry(QtCore.QRect(250, 580, 131, 30))
        self.synctimeBox.setObjectName("synctimeBox")
        self.localparticleComboBox = QtGui.QComboBox(self.centralwidget)
        self.localparticleComboBox.setGeometry(QtCore.QRect(263, 378, 111, 25))
        self.localparticleComboBox.setObjectName("localparticleComboBox")
        self.lineCheckBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.lineCheckBox_2.setGeometry(QtCore.QRect(210, 330, 51, 20))
        self.lineCheckBox_2.setObjectName("lineCheckBox_2")
        self.visitComboBox = QtGui.QComboBox(self.centralwidget)
        self.visitComboBox.setGeometry(QtCore.QRect(261, 484, 111, 25))
        self.visitComboBox.setObjectName("visitComboBox")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(227, 492, 31, 16))
        self.label_12.setObjectName("label_12")
        self.visitclosePushButton = QtGui.QPushButton(self.centralwidget)
        self.visitclosePushButton.setGeometry(QtCore.QRect(319, 458, 51, 20))
        self.visitclosePushButton.setObjectName("visitclosePushButton")
        self.quitpushButton = QtGui.QPushButton(self.centralwidget)
        self.quitpushButton.setGeometry(QtCore.QRect(315, 679, 71, 51))
        self.quitpushButton.setStyleSheet("color: rgb(0,0,255);\n"
"")
        self.quitpushButton.setObjectName("quitpushButton")
        self.strideSlider = QtGui.QSlider(self.centralwidget)
        self.strideSlider.setGeometry(QtCore.QRect(120, 430, 22, 61))
        self.strideSlider.setOrientation(QtCore.Qt.Vertical)
        self.strideSlider.setObjectName("strideSlider")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(120, 380, 51, 16))
        self.label_13.setObjectName("label_13")
        self.strideLabel = QtGui.QLabel(self.centralwidget)
        self.strideLabel.setGeometry(QtCore.QRect(100, 500, 51, 21))
        self.strideLabel.setText("")
        self.strideLabel.setObjectName("strideLabel")
        self.labframeCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.labframeCheckBox.setGeometry(QtCore.QRect(130, 250, 91, 20))
        self.labframeCheckBox.setObjectName("labframeCheckBox")
        self.x2minLabel = QtGui.QLabel(self.centralwidget)
        self.x2minLabel.setGeometry(QtCore.QRect(39, 181, 89, 16))
        self.x2minLabel.setText("")
        self.x2minLabel.setObjectName("x2minLabel")
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(222, 366, 51, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(170, 305, 61, 16))
        self.label_20.setObjectName("label_20")
        self.x2maxLabel = QtGui.QLabel(self.centralwidget)
        self.x2maxLabel.setGeometry(QtCore.QRect(202, 180, 89, 16))
        self.x2maxLabel.setText("")
        self.x2maxLabel.setObjectName("x2maxLabel")
        self.releaseButton = QtGui.QPushButton(self.centralwidget)
        self.releaseButton.setGeometry(QtCore.QRect(330, 130, 31, 31))
        self.releaseButton.setStyleSheet("color: rgb(0, 0, 255);\n"
"font:  12pt \"Helvetica\";\n"
"")
        self.releaseButton.setObjectName("releaseButton")
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(221, 382, 51, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 390, 31, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(53, 390, 31, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(83, 391, 31, 21))
        self.label_24.setObjectName("label_24")
        self.x1minLabel = QtGui.QLabel(self.centralwidget)
        self.x1minLabel.setGeometry(QtCore.QRect(40, 140, 89, 18))
        self.x1minLabel.setText("")
        self.x1minLabel.setObjectName("x1minLabel")
        self.slicevalueSlider2 = QtGui.QSlider(self.centralwidget)
        self.slicevalueSlider2.setGeometry(QtCore.QRect(10, 480, 101, 22))
        self.slicevalueSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.slicevalueSlider2.setObjectName("slicevalueSlider2")
        self.slicevalueLabel2 = QtGui.QLabel(self.centralwidget)
        self.slicevalueLabel2.setGeometry(QtCore.QRect(20, 500, 81, 21))
        self.slicevalueLabel2.setText("")
        self.slicevalueLabel2.setObjectName("slicevalueLabel2")
        self.strideSlider2 = QtGui.QSlider(self.centralwidget)
        self.strideSlider2.setGeometry(QtCore.QRect(160, 430, 22, 61))
        self.strideSlider2.setOrientation(QtCore.Qt.Vertical)
        self.strideSlider2.setObjectName("strideSlider2")
        self.strideLabel2 = QtGui.QLabel(self.centralwidget)
        self.strideLabel2.setGeometry(QtCore.QRect(150, 500, 51, 21))
        self.strideLabel2.setText("")
        self.strideLabel2.setObjectName("strideLabel2")
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(120, 400, 51, 16))
        self.label_14.setObjectName("label_14")
        self.savepushButton = QtGui.QPushButton(self.centralwidget)
        self.savepushButton.setGeometry(QtCore.QRect(320, 647, 61, 21))
        self.savepushButton.setStyleSheet("color: rgb(0, 0, 255);\n"
"font:  12pt \"Helvetica\";\n"
"")
        self.savepushButton.setObjectName("savepushButton")
        self.loadpushButton = QtGui.QPushButton(self.centralwidget)
        self.loadpushButton.setGeometry(QtCore.QRect(320, 620, 61, 21))
        self.loadpushButton.setStyleSheet("color: rgb(0, 0, 255);\n"
"font:  12pt \"Helvetica\";\n"
"")
        self.loadpushButton.setObjectName("loadpushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.stepSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change timestep stride</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.backwardtimeButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>previous time step</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.backwardtimeButton.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.forwardtimeButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>next time step</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.forwardtimeButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>time slide</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tiniSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>starting time index</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tmaxSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>final time index</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.animationButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>plot animation</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.animationButton.setText(QtGui.QApplication.translate("MainWindow", "animation", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Push <span style=\" font-weight:600;\">Plot</span> button</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>select a phase space</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.speciesComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>select a species</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rectangleCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>rectangle data selection</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rectangleCheckBox.setText(QtGui.QApplication.translate("MainWindow", "rect", None, QtGui.QApplication.UnicodeUTF8))
        self.lineCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>line data selection</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineCheckBox.setText(QtGui.QApplication.translate("MainWindow", "line", None, QtGui.QApplication.UnicodeUTF8))
        self.aspectCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>equal aspect ratio</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.aspectCheckBox.setText(QtGui.QApplication.translate("MainWindow", "equal aspect", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>select a field</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change to fields</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.particleButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change to particles</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.x1min.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Change AMR order</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "AMR Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "field/particle", None, QtGui.QApplication.UnicodeUTF8))
        self.xmax_3.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select 2D slice in 3D simulations</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.xmax_3.setText(QtGui.QApplication.translate("MainWindow", "2D slice in 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.slicevalueSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change the slice position</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pngCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>save png file</p><p>push <span style=\" font-weight:600;\">Plot </span>button!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pngCheckBox.setText(QtGui.QApplication.translate("MainWindow", ".png", None, QtGui.QApplication.UnicodeUTF8))
        self.movieCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>to create muliple images</p><p>push <span style=\" font-weight:600;\">animation</span> button!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.movieCheckBox.setText(QtGui.QApplication.translate("MainWindow", ".mp4", None, QtGui.QApplication.UnicodeUTF8))
        self.contrastSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change contrast</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.amrSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.yt3DPushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>3D yt volume rendering</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.yt3DPushButton.setText(QtGui.QApplication.translate("MainWindow", "3d yt", None, QtGui.QApplication.UnicodeUTF8))
        self.visitPushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>VisIt volume rendering</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.visitPushButton.setText(QtGui.QApplication.translate("MainWindow", "VisIt", None, QtGui.QApplication.UnicodeUTF8))
        self.rowpanelSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>add panels vertically</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "# of row", None, QtGui.QApplication.UnicodeUTF8))
        self.columnpanelSpinBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>add panels horizontally</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "# of column", None, QtGui.QApplication.UnicodeUTF8))
        self.synctimeBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>synchronize all the panels</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.synctimeBox.setText(QtGui.QApplication.translate("MainWindow", "sync time (multi)", None, QtGui.QApplication.UnicodeUTF8))
        self.localparticleComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>select local particles</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineCheckBox_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>line data selection</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineCheckBox_2.setText(QtGui.QApplication.translate("MainWindow", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.visitComboBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "VisIt", None, QtGui.QApplication.UnicodeUTF8))
        self.visitclosePushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>use this button ONLY to close VisIt</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.visitclosePushButton.setText(QtGui.QApplication.translate("MainWindow", "close", None, QtGui.QApplication.UnicodeUTF8))
        self.quitpushButton.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.strideSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change contrast</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "particle", None, QtGui.QApplication.UnicodeUTF8))
        self.labframeCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>line data selection</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labframeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "lab frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "local", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.releaseButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Return to orig. size</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.releaseButton.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "yx", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "xz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "yz", None, QtGui.QApplication.UnicodeUTF8))
        self.slicevalueSlider2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change the slice position</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.strideSlider2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>change contrast</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "stride", None, QtGui.QApplication.UnicodeUTF8))
        self.savepushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Return to orig. size</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.savepushButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.loadpushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Return to orig. size</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadpushButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))

