# Generated by Django 2.1.1 on 2018-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='success_url',
            field=models.CharField(default='/demo/', max_length=50, verbose_name='Success url'),
        ),
    ]
