# Generated by Django 2.1.2 on 2018-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0003_auto_20181003_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='feature_access',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Funksjonstilgang'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='success_url',
            field=models.CharField(default='/demo/', max_length=50, verbose_name='Nettadresse'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=20, verbose_name='Tilgangsnøkkel'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Gyldig'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kontakt epost'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='default_success_url',
            field=models.CharField(default='/demo/', max_length=50, verbose_name='Standard nettaddresse'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='demo_available_until_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Demo tilgjengelig til dato'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='final_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Endelig slipp dato'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='issue_handler',
            field=models.URLField(blank=True, null=True, verbose_name='Saksbehandlingssystem'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='project_page',
            field=models.URLField(blank=True, null=True, verbose_name='Prosjektside'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='requires_access_token',
            field=models.BooleanField(default=False, verbose_name='Tilgangsnøkkel nødvendig'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='status',
            field=models.CharField(blank=True, choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('rc', 'Utkast til ferdig versjon'), ('final', 'Ferdig versjon')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='text',
            field=models.TextField(default='Denne siden er under aktiv utvikling og kan derfor ha feil og mangler. Om du finner noe kan du melde dette til eposten eller melde saken til saksbehandlingssystemet oppgitt under.', verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='title',
            field=models.CharField(default='Demo site', max_length=100, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='demositesettings',
            name='version',
            field=models.CharField(blank=True, default='0.1.0', max_length=50, null=True, verbose_name='Versjon'),
        ),
    ]
