# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0 - 1.3), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.3
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot3
from purity_fb_1dot3.rest import ApiException
from purity_fb_1dot3.apis.network_interfaces_api import NetworkInterfacesApi


class TestNetworkInterfacesApi(unittest.TestCase):
    """ NetworkInterfacesApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot3.apis.network_interfaces_api.NetworkInterfacesApi()

    def tearDown(self):
        pass

    def test_create_network_interfaces(self):
        """
        Test case for create_network_interfaces

        
        """
        pass

    def test_delete_network_interfaces(self):
        """
        Test case for delete_network_interfaces

        
        """
        pass

    def test_list_network_interfaces(self):
        """
        Test case for list_network_interfaces

        
        """
        pass

    def test_update_network_interfaces(self):
        """
        Test case for update_network_interfaces

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
