# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0 - 1.3), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.3
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot3
from purity_fb_1dot3.rest import ApiException
from purity_fb_1dot3.models.hardware_connector_response import HardwareConnectorResponse


class TestHardwareConnectorResponse(unittest.TestCase):
    """ HardwareConnectorResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHardwareConnectorResponse(self):
        """
        Test HardwareConnectorResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = purity_fb_1dot3.models.hardware_connector_response.HardwareConnectorResponse()
        pass


if __name__ == '__main__':
    unittest.main()
