# coding: utf-8

"""
    Purity//FB REST Client

    Client for Purity//FB REST API (1.0 - 1.2), developed by [Pure Storage, Inc](http://www.purestorage.com/). Documentations can be found at [purity-fb.readthedocs.io](http://purity-fb.readthedocs.io/).

    OpenAPI spec version: 1.2
    Contact: info@purestorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import purity_fb_1dot2
from purity_fb_1dot2.rest import ApiException
from purity_fb_1dot2.apis.alerts_api import AlertsApi


class TestAlertsApi(unittest.TestCase):
    """ AlertsApi unit test stubs """

    def setUp(self):
        self.api = purity_fb_1dot2.apis.alerts_api.AlertsApi()

    def tearDown(self):
        pass

    def test_list_alerts(self):
        """
        Test case for list_alerts

        
        """
        pass

    def test_update_alerts(self):
        """
        Test case for update_alerts

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
