
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-13T17:15:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e75c2073c56199c7825eb4c6d910d69a9f8ac1fa",
 "version": "0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
