[tool.poetry]
name = "option"
version = "0.1.5"
description = "Rust like Option type in Python"
authors = ["Peijun Ma <peijun.ma@protonmail.com>"]
readme = "README.md"
license = "MIT"
repository="https://github.com/MaT1g3R/option"
homepage="https://github.com/MaT1g3R/option"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.620.0"
