
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-01T15:32:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b54f2eef372ec17dac8950828154844a5964666a",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
