
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cbd1833af62fdc6a2e1419e0399e5b93f9d3c183",
 "version": "0.5.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
