
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-18T16:46:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "81362cf8cb2a526bdab3b3d329af7e2500250d22",
 "version": "1.0.9a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
