# Generated by Django 2.1 on 2018-10-01 22:47

from django.db import migrations
import edc_base.sites.managers
import edc_locator.model_mixins.locator_model_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('edc_locator', '0011_auto_20181001_2103'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subjectlocator',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_locator.model_mixins.locator_model_mixin.LocatorManager()),
            ],
        ),
    ]
