# Generated by Django 2.1 on 2018-10-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_locator', '0013_auto_20181002_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
    ]
