# Generated by Django 2.1 on 2018-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_locator', '0014_auto_20181002_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
