
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-08T14:01:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0fc1e9032d8ecd8edc7f7d369b3d9b1672d09c06",
 "version": "2018.10.08a"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
