
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d846718f117ff202538367418e2dcb320fda337a",
 "version": "1999"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
