
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-02T19:21:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa1308eb98f935a924c03588656d90030806a600",
 "version": "v1.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
