
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-19T09:41:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c34c2ac724f9a2b9e59624a0878913d746877c17",
 "version": "6.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
