
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-26T14:29:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "84a1130f0a566b59599ff1038ee1880fff8d2886",
 "version": "v0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
