# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: pip install -r test-requirements.txt
  displayName: 'Install test-requirements'

- script: tox
  displayName: 'Test with tox'
