
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-18T11:37:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2712ed36980afd1b9e7cab0d35242dafbd94ad23",
 "version": "1.6.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
