
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-28T11:28:23+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ac2322fd1a5f9ff6b00905a9b76fc081b92cca7",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
