# Generated by Django 2.1 on 2018-10-01 20:56

from django.db import migrations
import edc_action_item.models.action_item
import edc_base.sites.managers


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0011_auto_20181001_2111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitem',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
                ('objects', edc_action_item.models.action_item.ActionItemManager()),
            ],
        ),
    ]
