# Generated by Django 2.1 on 2018-10-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0012_auto_20181001_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitem',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='actionitem',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalactionitem',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='historicalactionitem',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='parent_reference_identifier',
            new_name='parent_action_identifier',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='related_reference_identifier',
            new_name='related_action_identifier',
        ),
    ]
