# Generated by Django 2.1 on 2018-10-04 02:09

from django.db import migrations
import edc_action_item.models.action_item


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0014_auto_20181003_0614'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitem',
            managers=[
                ('on_site', edc_action_item.models.action_item.CurrentSiteManager()),
                ('objects', edc_action_item.models.action_item.ActionItemManager()),
            ],
        ),
    ]
