
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-11T22:08:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ac8b9ed34fd8ba24b6b531435cfca1aa9ecb1a6",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
