
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2018-09-12T11:34:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc284c07036b413f313cbff0b952dd0e8544f2d8",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
