
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-17T22:51:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7e57ee172a1913c8791047cd11d84d3964b51b6",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
