
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "90b34f935a56c54977c333fe7c6844cbbeb50611",
 "version": "1.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
