# Generated by Django 2.1.1 on 2018-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0002_auto_20181003_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demositesettings',
            name='text',
            field=models.TextField(default='This is a website under active development and may have bugs and lack lots of features. If you find anything you want to report use the contact email or issue handler below.', verbose_name='Text'),
        ),
    ]
