# Generated by Django 2.1 on 2018-10-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_action_item', '0010_auto_20181001_2103'),
        ('ambition_prn', '0006_auto_20180809_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathreport',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='deathreporttmg',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicaldeathreport',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicaldeathreporttmg',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusionw10',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AddField(
            model_name='studyterminationconclusionw10',
            name='action_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.ActionItem'),
        ),
        migrations.AlterField(
            model_name='deathreport',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deathreport',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deathreporttmg',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deathreporttmg',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeathreporttmg',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeathreporttmg',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusionw10',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusionw10',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusionw10',
            name='parent_reference_identifier',
            field=models.CharField(help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusionw10',
            name='related_reference_identifier',
            field=models.CharField(help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
    ]
