# Generated by Django 2.1 on 2018-10-04 02:09

from django.db import migrations, models
import edc_identifier.managers
import edc_visit_schedule.model_mixins.schedule_model_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0010_auto_20181002_0411'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='onschedule',
            managers=[
                ('on_site', edc_visit_schedule.model_mixins.schedule_model_mixin.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='onschedulew10',
            managers=[
                ('on_site', edc_visit_schedule.model_mixins.schedule_model_mixin.CurrentSiteManager()),
                ('objects', edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
        migrations.AlterField(
            model_name='deathreport',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='deathreporttmg',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldeathreporttmg',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalstudyterminationconclusionw10',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusionw10',
            name='action_identifier',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
